import hashlib
import importlib.util
from pathlib import Path
import os
import re
import tempfile
import time
import unittest
from zipfile import ZipFile

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.oxml.ns import qn
from docx.shared import Mm, Pt
from lxml import etree


PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORT = (
    Path(os.environ["REPORT_PATH"])
    if "REPORT_PATH" in os.environ
    else PROJECT_ROOT
    / "deliverables"
    / "关于巡防百科网站建设及推广应用情况的报告.docx"
)
PLAN = PROJECT_ROOT / "docs" / "superpowers" / "plans" / "2026-07-19-xunfang-project-report.md"
BUILDER = PROJECT_ROOT / ".codex-doc-review" / "build_report.py"
HEADINGS = [
    "一、项目建设背景与初衷",
    "二、总体建设思路与服务对象",
    "三、前期建设工作及阶段性成果",
    "四、建设方法与安全管理",
    "五、大队内部推广应用情况",
    "六、当前存在的不足",
    "七、下一步建设计划",
    "八、结语及建议",
]
HEADING_TREE = [
    (HEADINGS[0], "Heading 1"),
    ("（一）回应基层知识资料分散的现实问题", "Heading 2"),
    ("（二）推动工作知识由个人积累向集体共享转化", "Heading 2"),
    ("（三）坚持服务实战、规范稳妥的建设原则", "Heading 2"),
    (HEADINGS[1], "Heading 1"),
    ("（一）形成内容建设闭环", "Heading 2"),
    ("（二）突出双重服务定位", "Heading 2"),
    ("（三）明确网站使用边界", "Heading 2"),
    (HEADINGS[2], "Heading 1"),
    ("（一）搭建六大业务模块和三级内容架构", "Heading 2"),
    ("（二）完善分类浏览和站内查询能力", "Heading 2"),
    ("（三）完成阶段性内容整理和质量检查", "Heading 2"),
    (HEADINGS[3], "Heading 1"),
    ("（一）以标准化方式组织内容建设", "Heading 2"),
    ("（二）明确现阶段应用范围和持续治理要求", "Heading 2"),
    ("（三）严格区分公开来源核验与内部审批", "Heading 2"),
    ("（四）建立问题发现和整改复核机制", "Heading 2"),
    (HEADINGS[4], "Heading 1"),
    ("（一）推广范围保持在大队内部", "Heading 2"),
    ("（二）初步覆盖日常巡逻和理论学习场景", "Heading 2"),
    ("（三）依据一线反馈持续优化", "Heading 2"),
    (HEADINGS[5], "Heading 1"),
    ("（一）内容覆盖仍需持续拓展", "Heading 2"),
    ("（二）更新维护机制还需制度化", "Heading 2"),
    ("（三）应用效果缺少量化评估", "Heading 2"),
    ("（四）扩大使用范围前仍需严格审查", "Heading 2"),
    (HEADINGS[6], "Heading 1"),
    (HEADINGS[7], "Heading 1"),
    ("（一）继续在审核把关前提下开展内部试用", "Heading 2"),
    ("（二）建立内容共建与定期更新机制", "Heading 2"),
    ("（三）坚持成熟一项、评估一项、稳妥推进", "Heading 2"),
]

W14_NS = "http://schemas.microsoft.com/office/word/2010/wordml"
FIXED_ZIP_TIMESTAMP = (2000, 1, 1, 0, 0, 0)
FIXED_ZIP_EXTERNAL_ATTR = 0x20
WORD_TRUE_VALUES = {"1", "true", "on", "yes"}


def _load_builder_module():
    spec = importlib.util.spec_from_file_location("xunfang_report_builder", BUILDER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _effective_paragraph_value(paragraph, name):
    direct = getattr(paragraph.paragraph_format, name)
    if direct is not None:
        return direct
    return getattr(paragraph.style.paragraph_format, name)


def _word_boolean_is_enabled(element) -> bool:
    value = element.get(qn("w:val"))
    return value is None or value.strip().lower() in WORD_TRUE_VALUES


def _package_hygiene_violations(path: Path) -> list[str]:
    violations = set()
    absolute_path = re.compile(
        r"(?:(?<![A-Za-z0-9])[A-Za-z]:[\\/]|/Users/|/home/|/mnt/data/|file:///)",
        re.I,
    )
    secret_value = re.compile(
        r"(?:bearer\s+[A-Za-z0-9._~+/=-]{8,}|"
        r"(?:api[_ -]?key|password|token)\s*[:=]\s*\S+|"
        r"(?:密码|口令|令牌|密钥)\s*[:：=]\s*\S+|"
        r"\b[a-f0-9]{32,}\b)",
        re.I,
    )
    unfinished = re.compile(r"\b(?:TODO|TBD|FIXME|XXX|DRAFT)\b", re.I)
    citation_token = re.compile(
        r":codex-file-citation\{|cite|turn\d+(?:search|open|fetch|view)\d+|【\d+†[^】]*】",
        re.I,
    )
    tool_token = re.compile(r"python-docx|generated by python-docx|libreoffice|openai|chatgpt|normal\.dotm", re.I)

    with ZipFile(path) as archive:
        for name in archive.namelist():
            data = archive.read(name)
            if not (name.endswith(".xml") or name.endswith(".rels")):
                continue
            root = etree.fromstring(data)

            if name == "docProps/app.xml":
                for element in root:
                    local_name = etree.QName(element).localname
                    if local_name in {"Application", "AppVersion", "Template"}:
                        value = (element.text or "").strip()
                        if value:
                            violations.add(f"{name}: non-neutral {local_name}={value!r}")

            if name == "docProps/core.xml":
                for element in root:
                    local_name = etree.QName(element).localname
                    value = (element.text or "").strip()
                    if local_name == "title":
                        if value != "关于“巡防百科”网站建设及推广应用情况的报告":
                            violations.add(f"{name}: unexpected title={value!r}")
                    elif value:
                        violations.add(f"{name}: non-neutral {local_name}={value!r}")

            values = []
            for element in root.iter():
                element_name = etree.QName(element).localname
                element_namespace = etree.QName(element).namespace
                if element_name.lower().startswith("rsid"):
                    violations.add(f"{name}: revision element {element_name}")
                if element_namespace == W14_NS and element_name == "docId":
                    violations.add(f"{name}: w14:docId")
                if element.text:
                    values.append(element.text)
                for attribute_name, attribute_value in element.attrib.items():
                    attribute_local_name = etree.QName(attribute_name).localname
                    if attribute_local_name.lower().startswith("rsid"):
                        violations.add(
                            f"{name}: revision attribute {attribute_local_name}"
                        )
                    values.append(attribute_value)

            for value in values:
                for label, pattern in (
                    ("tool identifier", tool_token),
                    ("internal path", absolute_path),
                    ("secret", secret_value),
                    ("unfinished marker", unfinished),
                    ("tool citation token", citation_token),
                ):
                    match = pattern.search(value)
                    if match:
                        violations.add(f"{name}: {label} {match.group(0)!r}")
    return sorted(violations)


class ReportTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.doc = Document(REPORT)
        cls.text = "\n".join(p.text for p in cls.doc.paragraphs)

    def all_document_paragraphs(self):
        for paragraph in self.doc.paragraphs:
            yield paragraph
        for table in self.doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    yield from cell.paragraphs
        for section in self.doc.sections:
            for container in (section.header, section.footer):
                yield from container.paragraphs
                for table in container.tables:
                    for row in table.rows:
                        for cell in row.cells:
                            yield from cell.paragraphs

    def text_runs(self, paragraph):
        runs = [run for run in paragraph.runs if run.text.strip()]
        self.assertTrue(runs, f"paragraph has no text runs: {paragraph.text!r}")
        return runs

    def assert_font(self, paragraph, names, size, bold=None):
        for run in self.text_runs(paragraph):
            self.assertIn(run.font.name, names)
            self.assertAlmostEqual(run.font.size.pt, size, places=1)
            if bold is not None:
                self.assertEqual(run.bold, bold)

    def test_required_content(self):
        self.assertEqual(
            self.doc.paragraphs[0].text.replace("\n", ""),
            "关于“巡防百科”网站建设及推广应用情况的报告",
        )
        for heading in HEADINGS:
            self.assertIn(heading, self.text)
        for fact in [
            "六大业务模块",
            "87条",
            "121个页面",
            "大队内部",
            "日常巡逻",
            "理论学习",
            "反馈",
            "优化",
        ]:
            self.assertIn(fact, self.text)

    def test_sensitive_content_absent(self):
        content = "\n".join(paragraph.text for paragraph in self.all_document_paragraphs())
        for forbidden in [
            "口令",
            "密码",
            "SHA-256",
            "SHA-1",
            "SHA-512",
            "MD5",
            "哈希",
            "摘要",
            "Token",
            "token",
            "令牌",
            "Bearer",
            "API Key",
            "API密钥",
            "GitHub",
            "GitLab",
            "仓库",
            "repository",
            "服务器地址",
            "服务器IP",
            "localhost",
            "http://",
            "https://",
            "index.lock",
            "F:\\",
            "C:\\",
            "\\\\",
        ]:
            self.assertNotIn(forbidden, content)
        self.assertIsNone(
            re.search(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", content),
            "report must not disclose a server IP address",
        )

    def test_core_properties_are_neutral(self):
        properties = self.doc.core_properties
        self.assertEqual(
            properties.title,
            "关于“巡防百科”网站建设及推广应用情况的报告",
        )
        for name in (
            "author",
            "last_modified_by",
            "comments",
            "subject",
            "keywords",
            "category",
        ):
            self.assertIn(
                getattr(properties, name),
                (None, ""),
                f"core property {name} must be blank",
            )

    def test_package_contains_no_metadata_or_hygiene_violations(self):
        with ZipFile(REPORT) as archive:
            styles = archive.read("word/styles.xml").decode("utf-8")
        for built_in_style in ("Normal", "Heading1", "Heading2", "Footer"):
            self.assertIn(
                built_in_style,
                styles,
                f"false-positive guard requires built-in style {built_in_style}",
            )
        violations = _package_hygiene_violations(REPORT)
        self.assertEqual(
            violations,
            [],
            "package metadata/hygiene violations:\n" + "\n".join(violations),
        )

    def test_fresh_build_is_byte_deterministic_and_matches_committed_artifact(self):
        builder = _load_builder_module()
        with tempfile.TemporaryDirectory(prefix="xunfang-report-determinism-") as temp_dir:
            first = Path(temp_dir) / "first.docx"
            second = Path(temp_dir) / "second.docx"
            builder.build_report(first)
            time.sleep(2.2)
            builder.build_report(second)
            first_bytes = first.read_bytes()
            second_bytes = second.read_bytes()
            with ZipFile(first) as archive:
                infos = archive.infolist()
                archive_names = [info.filename for info in infos]
                archive_timestamps = {info.date_time for info in infos}
                archive_metadata_is_stable = all(
                    info.create_system == 0
                    and info.external_attr == FIXED_ZIP_EXTERNAL_ATTR
                    and info.internal_attr == 0
                    and info.extra == b""
                    and info.comment == b""
                    for info in infos
                )
        committed_bytes = REPORT.read_bytes()
        builds_equal = first_bytes == second_bytes
        committed_equal = committed_bytes == first_bytes
        entry_order_is_stable = archive_names == sorted(archive_names)
        timestamps_are_fixed = archive_timestamps == {FIXED_ZIP_TIMESTAMP}
        hashes = {
            "first": hashlib.sha256(first_bytes).hexdigest(),
            "second": hashlib.sha256(second_bytes).hexdigest(),
            "committed": hashlib.sha256(committed_bytes).hexdigest(),
        }
        self.assertTrue(
            builds_equal
            and committed_equal
            and entry_order_is_stable
            and timestamps_are_fixed
            and archive_metadata_is_stable,
            (
                f"builds_equal={builds_equal}, committed_equal={committed_equal}, "
                f"entry_order_is_stable={entry_order_is_stable}, "
                f"timestamps={archive_timestamps}, "
                f"archive_metadata_is_stable={archive_metadata_is_stable}, hashes={hashes}"
            ),
        )

    def test_plan_uses_portable_runtime_variables_and_current_contract(self):
        plan = PLAN.read_text(encoding="utf-8")
        self.assertNotIn("C:\\Users\\", plan)
        self.assertNotRegex(plan, r"\b5\s+tests\b|5/5|5\s*个测试|5\s*项测试")
        self.assertIn("八、结语及建议", plan)
        self.assertNotIn("八、结语及有关建议", plan)
        self.assertEqual(plan.count("$BUNDLED_PYTHON ="), 1)
        self.assertEqual(plan.count("$DOCS_SKILL_DIR ="), 1)
        for command in (
            "& $BUNDLED_PYTHON '.codex-doc-review/test_report.py' -v",
            "& $BUNDLED_PYTHON '.codex-doc-review/build_report.py'",
            "& $BUNDLED_PYTHON $TABLE_GEOMETRY",
        ):
            self.assertIn(command, plan)

    def test_page_geometry(self):
        for section in self.doc.sections:
            self.assertAlmostEqual(section.page_width.mm, Mm(210).mm, places=1)
            self.assertAlmostEqual(section.page_height.mm, Mm(297).mm, places=1)
            for actual, expected in [
                (section.top_margin.mm, 37),
                (section.bottom_margin.mm, 35),
                (section.left_margin.mm, 28),
                (section.right_margin.mm, 26),
            ]:
                self.assertAlmostEqual(actual, expected, places=1)

    def test_title_and_heading_formatting(self):
        title = self.doc.paragraphs[0]
        self.assertEqual(
            title.text,
            "关于“巡防百科”网站建设及\n推广应用情况的报告",
        )
        self.assertEqual(title.alignment, WD_ALIGN_PARAGRAPH.CENTER)
        for run in self.text_runs(title):
            self.assertEqual(run.font.name, "方正小标宋简体")
            self.assertAlmostEqual(run.font.size.pt, 22, places=1)
            self.assertIsNotNone(run._element.rPr)
            self.assertEqual(
                run._element.rPr.rFonts.get(qn("w:eastAsia")),
                "方正小标宋简体",
            )
        actual_heading_tree = [
            (paragraph.text, paragraph.style.name)
            for paragraph in self.doc.paragraphs
            if paragraph.style.name in {"Heading 1", "Heading 2"}
        ]
        self.assertEqual(actual_heading_tree, HEADING_TREE)
        for paragraph in self.doc.paragraphs:
            if paragraph.style.name not in {"Heading 1", "Heading 2"}:
                continue
            level = 1 if paragraph.style.name == "Heading 1" else 2
            expected_space_before = 14 if level == 1 else 8
            self.assertEqual(paragraph.alignment, WD_ALIGN_PARAGRAPH.LEFT)
            self.assertAlmostEqual(paragraph.paragraph_format.first_line_indent.pt, 0, places=1)
            self.assertEqual(
                _effective_paragraph_value(paragraph, "line_spacing_rule"),
                WD_LINE_SPACING.EXACTLY,
            )
            self.assertAlmostEqual(
                _effective_paragraph_value(paragraph, "line_spacing").pt,
                Pt(28).pt,
                places=1,
            )
            self.assertAlmostEqual(
                _effective_paragraph_value(paragraph, "space_before").pt,
                Pt(expected_space_before).pt,
                places=1,
            )
            self.assertAlmostEqual(
                _effective_paragraph_value(paragraph, "space_after").pt,
                0,
                places=1,
            )
            self.assertIs(
                _effective_paragraph_value(paragraph, "keep_with_next"),
                True,
            )
            if level == 1:
                for run in self.text_runs(paragraph):
                    self.assertEqual(run.font.name, "黑体")
                    self.assertAlmostEqual(run.font.size.pt, 16, places=1)
                    self.assertIsNotNone(run._element.rPr)
                    self.assertEqual(
                        run._element.rPr.rFonts.get(qn("w:eastAsia")), "黑体"
                    )
            else:
                self.assert_font(paragraph, ["楷体_GB2312"], 16, bold=True)

    def test_body_paragraph_formatting(self):
        style = self.doc.styles["Normal"]
        self.assertAlmostEqual(style.font.size.pt, Pt(16).pt, places=1)
        self.assertEqual(style.font.name, "仿宋_GB2312")
        self.assertAlmostEqual(style.paragraph_format.line_spacing.pt, Pt(28).pt, places=1)
        bodies = [
            paragraph
            for paragraph in self.doc.paragraphs
            if paragraph.text
            and paragraph.style.name == "Normal"
            and paragraph != self.doc.paragraphs[0]
            and paragraph.text not in HEADINGS
            and not re.match(r"^（[一二三四五六七八九十]+）", paragraph.text)
            and not paragraph.text.startswith("（汇报人：")
            and not paragraph.text.startswith("____年")
        ]
        self.assertTrue(bodies, "report must contain at least one body paragraph")
        for body in bodies:
            self.assertEqual(body.alignment, WD_ALIGN_PARAGRAPH.JUSTIFY)
            self.assert_font(body, ["仿宋_GB2312"], 16)
            self.assertEqual(body.paragraph_format.line_spacing_rule, WD_LINE_SPACING.EXACTLY)
            self.assertAlmostEqual(body.paragraph_format.line_spacing.pt, Pt(28).pt, places=1)
            self.assertAlmostEqual(body.paragraph_format.first_line_indent.pt, Pt(32).pt, places=1)

    def test_footer_page_number_formatting(self):
        for section in self.doc.sections:
            self.assertAlmostEqual(section.footer_distance.mm, Mm(28).mm, places=1)
            footer = section.footer.paragraphs[0]
            self.assertEqual(footer.alignment, WD_ALIGN_PARAGRAPH.CENTER)
            self.assertEqual(footer.text, "— 1 —")
            tokens = []
            for element in footer._p.iter():
                if element.tag == qn("w:fldChar"):
                    tokens.append(("field", element.get(qn("w:fldCharType"))))
                elif element.tag == qn("w:instrText"):
                    tokens.append(("instruction", (element.text or "").strip()))
                elif element.tag == qn("w:t") and element.text:
                    tokens.append(("text", element.text))
            self.assertEqual(
                tokens,
                [
                    ("text", "— "),
                    ("field", "begin"),
                    ("instruction", "PAGE"),
                    ("field", "separate"),
                    ("text", "1"),
                    ("field", "end"),
                    ("text", " —"),
                ],
            )
            self.assertEqual(len(footer.runs), 4)
            for run in footer.runs:
                self.assertEqual(run.font.name, "宋体")
                self.assertAlmostEqual(run.font.size.pt, 14, places=1)
                self.assertEqual(run._element.rPr.rFonts.get(qn("w:ascii")), "宋体")
                self.assertEqual(run._element.rPr.rFonts.get(qn("w:eastAsia")), "宋体")

    def test_summary_table_geometry_and_row_height_contract(self):
        self.assertEqual(len(self.doc.tables), 1)
        table = self.doc.tables[0]
        expected_widths = [1814, 3288, 3742]
        self.assertEqual(len(table.columns), len(expected_widths))

        tbl_pr = table._tbl.tblPr
        tbl_w = tbl_pr.first_child_found_in("w:tblW")
        self.assertIsNotNone(tbl_w)
        self.assertEqual(tbl_w.get(qn("w:type")), "dxa")
        self.assertEqual(int(tbl_w.get(qn("w:w"))), sum(expected_widths))
        tbl_ind = tbl_pr.first_child_found_in("w:tblInd")
        self.assertIsNotNone(tbl_ind)
        self.assertEqual(tbl_ind.get(qn("w:type")), "dxa")
        self.assertEqual(tbl_ind.get(qn("w:w")), "120")

        grid_widths = [int(col.get(qn("w:w"))) for col in table._tbl.tblGrid]
        self.assertEqual(grid_widths, expected_widths)
        self.assertEqual(sum(grid_widths), int(tbl_w.get(qn("w:w"))))

        header_pr = table.rows[0]._tr.get_or_add_trPr()
        header = header_pr.first_child_found_in("w:tblHeader")
        self.assertIsNotNone(header)
        self.assertEqual(header.get(qn("w:val")), "true")
        for row in table.rows:
            tr_pr = row._tr.trPr
            cant_split = (
                tr_pr.first_child_found_in("w:cantSplit")
                if tr_pr is not None
                else None
            )
            self.assertIsNotNone(
                cant_split,
                "summary table rows must not split across pages",
            )
            self.assertTrue(
                _word_boolean_is_enabled(cant_split),
                f"w:cantSplit must be enabled, got w:val={cant_split.get(qn('w:val'))!r}",
            )
            self.assertTrue(
                tr_pr is None or tr_pr.first_child_found_in("w:trHeight") is None,
                "summary table must not use fixed row heights",
            )
            self.assertEqual(len(row.cells), len(expected_widths))
            for cell, expected_width in zip(row.cells, expected_widths):
                tc_w = cell._tc.tcPr.first_child_found_in("w:tcW")
                self.assertIsNotNone(tc_w)
                self.assertEqual(tc_w.get(qn("w:type")), "dxa")
                self.assertEqual(int(tc_w.get(qn("w:w"))), expected_width)

    def test_signature_placeholders(self):
        self.assertIn("（汇报人：________）", self.text)
        self.assertIn("____年__月__日", self.text)


if __name__ == "__main__":
    unittest.main()
